ScottFundamentals/Models/Restaurant.cs
using System;

namespace ScottFundamentals.Models
{
    public class Restaurant
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public CuisineType CuisineType { get; set; }
        public int CuisineId { get; set; }
        public DateTime Since { get; set; }
        
    }

    public class CuisineType
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

ScottFundamentals/Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Restaurant.DataAccess.Ef.Infrastructure;
using Restaurant.Models;
using Restaurant.Models.Dtos;

namespace ScottFundamentals.Controllers
{
    public class RestaurantsController : Controller
    {
        private readonly RestaurantDbContext _context;

        public RestaurantsController(RestaurantDbContext context)
        {
            _context = context;
        }

        // GET: Restaurants
        public async Task<IActionResult> Index()
        {
            var model = await (from r in _context.Restaurants.AsNoTracking()
                               select new RestaurantVm()
                               {
                                   CuisineType = r.CuisineType,
                                   Id = r.Id,
                                   Name = r.Name,
                                   Since = r.Since,
                                   CoffeeShop = r.CoffeeShop
                               }).ToListAsync();

            return View(model);
        }

        // GET: Restaurants/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurant = await _context.Restaurants.AsNoTracking()
                .Select(x => new RestaurantVm()
                {
                    Name = x.Name,
                    Id = x.Id,
                    Since = x.Since,
                    CuisineType = x.CuisineType,
                    CoffeeShop = x.CoffeeShop
                })
                .FirstOrDefaultAsync(m => m.Id == id);

            if (restaurant == null)
            {
                return NotFound();
            }

            return View(restaurant);
        }

        // GET: Restaurants/Create
        public async Task<IActionResult> Create()
        {
            var allCuisine = await _context.CuisineTypes.AsNoTracking().OrderBy(x => x.Name).ToListAsync();

            var model = new RestaurantEditVm() { AllCuisineTypes = allCuisine };

            return View(model);
        }

        // POST: Restaurants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,CuisineTypeId,Since,CoffeeShop")] RestaurantEditVm restaurantVm)
        {
            if (ModelState.IsValid)
            {
                var restaurant = new Restaurant.Models.Restaurant()
                {
                    Name = restaurantVm.Name,
                    CuisineTypeId = restaurantVm.CuisineTypeId,
                    //CuisineType = restaurantVm.CuisineType,
                    Since = restaurantVm.Since,
                    CoffeeShop = restaurantVm.CoffeeShop,
                    Id = Guid.NewGuid()
                };

                _context.Add(restaurant);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(restaurantVm);
        }

        // GET: Restaurants/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurant = await _context.Restaurants.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id);

            if (restaurant == null)
            {
                return NotFound();
            }

            var allCuisine = await _context.CuisineTypes.AsNoTracking().OrderBy(x => x.Name).ToListAsync();

            var model = new RestaurantEditVm()
            {
                AllCuisineTypes = allCuisine,
                //CuisineType = restaurant.CuisineType,
                CuisineTypeId = restaurant.CuisineTypeId,
                Id = restaurant.Id,
                Name = restaurant.Name,
                Since = restaurant.Since,
                CoffeeShop = restaurant.CoffeeShop
            };

            return View(model);
        }

        // POST: Restaurants/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,CuisineTypeId,Since,CoffeeShop")] RestaurantEditVm restaurantVm)
        {
            if (id != restaurantVm.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var model = new Restaurant.Models.Restaurant()
                    {
                        CuisineTypeId = restaurantVm.CuisineTypeId,
                        Id = restaurantVm.Id,
                        Name = restaurantVm.Name,
                        Since = restaurantVm.Since,
                        CoffeeShop = restaurantVm.CoffeeShop
                    };

                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RestaurantExists(restaurantVm.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(restaurantVm);
        }

        // GET: Restaurants/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurant = await _context.Restaurants.AsNoTracking()
                .Select(x => new RestaurantVm()
                {
                    Name = x.Name,
                    Id = x.Id,
                    Since = x.Since,
                    CuisineType = x.CuisineType,
                    CoffeeShop = x.CoffeeShop
                })
                .FirstOrDefaultAsync(m => m.Id == id);

            if (restaurant == null)
            {
                return NotFound();
            }

            return View(restaurant);
        }

        // POST: Restaurants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var restaurant = await _context.Restaurants.FindAsync(id);
            _context.Restaurants.Remove(restaurant);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool RestaurantExists(Guid id)
        {
            return _context.Restaurants.Any(e => e.Id == id);
        }

        [HttpGet]
        public async Task<IActionResult> Search()
        {
            var allCuisine = await _context.CuisineTypes.AsNoTracking().OrderBy(x => x.Name).ToListAsync();

            var model = new RestaurantSearchFormModel()
            {
                AllCuisineTypes = allCuisine,
                Results = new List<Result>(),
                Since = new DateTime(2000,1,1)
            };
            
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Search(RestaurantSearchFormModel searchModel)
        {
            var q = _context.Restaurants.AsQueryable();
            if (!string.IsNullOrWhiteSpace(searchModel.Name))
            {
                q = q.Where(x => x.Name.Contains(searchModel.Name));
            }

            if (searchModel.CoffeeShop)
            {
                q = q.Where(x => x.CoffeeShop == searchModel.CoffeeShop);
            }

            if (searchModel.CuisineTypeId != 0)
            {
                q = q.Where(x => x.CuisineTypeId == searchModel.CuisineTypeId);
            }

            if (searchModel.Since.Year > 1900)
            {
                q = q.Where(x => x.Since.Date >= searchModel.Since.Date);
            }

            var items = await q
                .AsNoTracking()
                .Select(r => new Result()
                {
                    CuisineType = r.CuisineType,
                    Id = r.Id,
                    Name = r.Name,
                    Since = r.Since,
                    CoffeeShop = r.CoffeeShop
                })
                .ToListAsync();

            var allCuisine = await _context.CuisineTypes.AsNoTracking().OrderBy(x => x.Name).ToListAsync();
            searchModel.Results = items;
            searchModel.AllCuisineTypes = allCuisine;

            //return PartialView("_SearchResult", searchModel);
            return View(searchModel);
        }
    }
}

ScottFundamentals/ViewComponents/SearchRestaurantViewComponent.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Restaurant.DataAccess.Ef.Infrastructure;
using Restaurant.Models.Dtos;

namespace ScottFundamentals.ViewComponents
{
    public class SearchRestaurantViewComponent : ViewComponent
    {
        private readonly RestaurantDbContext _context;

        public SearchRestaurantViewComponent(RestaurantDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(string name, bool coffeeShop)
        {
            var items = await _context.Restaurants
                .Where(x => x.Name.Contains(name) && x.CoffeeShop == coffeeShop)
                .AsNoTracking()
                .Select(r => new RestaurantVm()
                {
                    CuisineType = r.CuisineType,
                    Id = r.Id,
                    Name = r.Name,
                    Since = r.Since,
                    CoffeeShop = r.CoffeeShop
                })
                .ToListAsync();

            return View(items);
        }
    }
}

ScottFundamentals/Views/Restaurants/Create.cshtml
@model Restaurant.Models.Dtos.RestaurantEditVm

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="CuisineTypeId" class="control-label"></label>
                <select asp-for="CuisineTypeId" class="form-control" asp-items="ViewBag.CuisineTypeId"></select>
            </div>*@
            <div class="form-group">
                <label asp-for="CuisineTypeId" class="control-label"></label>
                <select asp-for="CuisineTypeId" class="form-control"
                        asp-items="@(new SelectList(Model.AllCuisineTypes,"Id","Name"))">
                    <option>Please select one</option>
                </select>
                <span asp-validation-for="CuisineTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Since" class="control-label"></label>
                <input asp-for="Since" class="form-control" />
                <span asp-validation-for="Since" class="text-danger"></span>
            </div>
            
            <label asp-for="CoffeeShop" class="control-label">CoffeeShop</label>
            <div class="form-group form-check-inline">
                <input class="form-check-input" id="CoffeeShopYes" type="radio" asp-for="CoffeeShop" value="true"/>
                <label class="form-check-label" for="CoffeeShopYes">Yes</label>
            </div> 
            <div class="form-group form-check-inline">
                <input class="form-check-input" id="CoffeeShopNo" type="radio" asp-for="CoffeeShop" value="false"/>
                <label class="form-check-label" for="CoffeeShopNo">No</label>
            </div>
            
            

            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ScottFundamentals/Views/Restaurants/CreateOld.cshtml
@model Restaurant.Models.Dtos.RestaurantEditVm

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CuisineTypeId" class="control-label"></label>
                <select asp-for="CuisineTypeId" class="form-control"
                        asp-items="@(new SelectList(Model.AllCuisineTypes,"Id","Name"))">
                    <option>Please select one</option>
                </select>
                <span asp-validation-for="CuisineTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Since" class="control-label"></label>
                <input asp-for="Since" class="form-control" />
                <span asp-validation-for="Since" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="CoffeeShop" /> @Html.DisplayNameFor(model => model.CoffeeShop)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ScottFundamentals/Views/Restaurants/Delete.cshtml
@model Restaurant.Models.Dtos.RestaurantVm

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CuisineType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CuisineType.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Since)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Since)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CoffeeShop)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CoffeeShop)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ScottFundamentals/Views/Restaurants/Details.cshtml
@model Restaurant.Models.Dtos.RestaurantVm

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CuisineType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CuisineType.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Since)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Since)
        </dd> 
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CoffeeShop)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CoffeeShop)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

<div>
    @await Component.InvokeAsync("SearchRestaurant", new { name ="2", coffeeShop = false })
</div>

ScottFundamentals/Views/Restaurants/Edit.cshtml
@model Restaurant.Models.Dtos.RestaurantEditVm

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CuisineType" class="control-label"></label>
                <select asp-for="CuisineTypeId" class="form-control"
                        asp-items="@(new SelectList(Model.AllCuisineTypes,"Id","Name"))">
                    <option>Please select one</option>
                </select>
                <span asp-validation-for="CuisineType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Since" class="control-label"></label>
                <input asp-for="Since" class="form-control" />
                <span asp-validation-for="Since" class="text-danger"></span>
            </div>
            
            <label asp-for="CoffeeShop" class="control-label">CoffeeShop</label>
            <div class="form-group form-check-inline">
                <input class="form-check-input" id="CoffeeShopYes" type="radio" asp-for="CoffeeShop" value="true"/>
                <label class="form-check-label" for="CoffeeShopYes">Yes</label>
            </div> 
            <div class="form-group form-check-inline">
                <input class="form-check-input" id="CoffeeShopNo" type="radio" asp-for="CoffeeShop" value="false"/>
                <label class="form-check-label" for="CoffeeShopNo">No</label>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ScottFundamentals/Views/Restaurants/Index.cshtml
@model IEnumerable<Restaurant.Models.Dtos.RestaurantVm>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

@foreach (var item in @Model)
{
    <partial name="_Summary" model="item" />
}

ScottFundamentals/Views/Restaurants/Search.cshtml
@model Restaurant.Models.Dtos.RestaurantSearchFormModel

<div >
   
    <form asp-action="Search"
          data-ajax="true"
          data-ajax-method="POST"
          data-ajax-mode="replace"
          data-ajax-update="#ajaxresult">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group col-md-4">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        @*<div class="form-group">
                <label asp-for="CuisineTypeId" class="control-label"></label>
                <select asp-for="CuisineTypeId" class="form-control" asp-items="ViewBag.CuisineTypeId"></select>
            </div>*@
        <div class="form-group col-md-4">
            <label asp-for="CuisineType" class="control-label"></label>
            <select asp-for="CuisineTypeId" class="form-control"
                    asp-items="@(new SelectList(Model.AllCuisineTypes, "Id", "Name"))">
                <option>Please select one</option>
            </select>
            <span asp-validation-for="CuisineType" class="text-danger"></span>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="Since" class="control-label"></label>
            <input asp-for="Since" class="form-control" />
            <span asp-validation-for="Since" class="text-danger"></span>
        </div>

        <div class="col-md-4">
            <label asp-for="CoffeeShop" class="control-label">CoffeeShop</label>
            <div class="form-group form-check-inline">
                <input class="form-check-input" id="CoffeeShopYes" type="radio" asp-for="CoffeeShop" value="true" />
                <label class="form-check-label" for="CoffeeShopYes">Yes</label>
            </div>
            <div class="form-group form-check-inline">
                <input class="form-check-input" id="CoffeeShopNo" type="radio" asp-for="CoffeeShop" value="false" />
                <label class="form-check-label" for="CoffeeShopNo">No</label>
            </div>
        </div>





        <div class="form-group">
            <input type="submit" value="Search" class="btn btn-primary" />
        </div>

     
    </form>

</div>
@*<div id="ajaxresult">
                @await Html.PartialAsync("_SearchResult", Model)

            </div>*@


<section>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CuisineType)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Since)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CoffeeShop)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Results)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CuisineType.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Since)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CoffeeShop)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</section>

ScottFundamentals/Views/Restaurants/_SearchResult.cshtml
@model Restaurant.Models.Dtos.RestaurantSearchFormModel

<section>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CuisineType)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Since)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CoffeeShop)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Results)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CuisineType.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Since)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CoffeeShop)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</section>

ScottFundamentals/Views/Restaurants/_Summary.cshtml
@model Restaurant.Models.Dtos.RestaurantVm

<section>
    <h3>@Model.Name</h3>

    <div>Cuisine: @Model.CuisineType.Name</div>
    <div>Since: @Model.Since</div>
    
    @{
        if (@Model.CoffeeShop)
        {
            <div>Has Coffee Shop</div>
        }
        else
        {
            <div>No CoffeeShop</div>
        }
    }
    <div>
        <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
        <a asp-action="Details" asp-route-id="@Model.Id">Details</a> |
        <a asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
    </div>
    <hr/>
</section>